workflows:
  ios-ionic-release:
    name: iOS Ionic Release
    environment:
      xcode: latest
      cocoapods: default
      node: 18.16.0
      ios_signing:
        certificates:
          - certificate_url: file://./certs/CertVPS.p12
            certificate_password: Uh1dtx0*
        provisioning_profiles:
          - file://./certs/ProfileVPS.mobileprovision
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build Ionic project
        script: |
          npm run build
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Build iOS app
        script: |
          xcodebuild clean archive \
            -workspace "App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_archive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=X693B2FAZ3 \
            PROVISIONING_PROFILE_SPECIFIER=ProfileVPS \
            PRODUCT_BUNDLE_IDENTIFIER=com.vapaesa
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_archive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_export
    artifacts:
      - ios_export/*.ipa
