workflows:
  ios-workflow:
    name: Build iOS
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.vapaesa"
        APP_NAME: "VapaesaApp"
        CERTIFICATE_PASSWORD: "Uh1dtx0*"
      node: 20.0.0
      xcode: latest
    scripts:
      - name: Install Ionic CLI
        script: |
          npm install -g @ionic/cli
      - name: Install dependencies
        script: |
          npm ci
      - name: Build Ionic web assets
        script: |
          ionic build --prod
      - name: Sync Capacitor for iOS
        script: |
          ionic cap sync ios
      - name: Prepare iOS
        script: |
          cd ios/App
          pod install
      - name: Import provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp certs/ProvProfileVPSDis.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Import signing certificate
        script: |
          security delete-keychain build.keychain || true
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certs/CodeMagicCertVapaesa.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Fix code signing in Pods (disable manual signing)
        script: |
          echo "🔧 Desactivando firma manual en los Pods..."
          find ./ios/App/Pods -name '*.xcodeproj' | while read project; do
            echo "   ➤ Corrigiendo $project"
            sed -i '' 's/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/g' "$project/project.pbxproj"
            sed -i '' '/PROVISIONING_PROFILE/d' "$project/project.pbxproj"
            sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' "$project/project.pbxproj"
            sed -i '' '/DEVELOPMENT_TEAM/d' "$project/project.pbxproj"
            sed -i '' '/CODE_SIGN_IDENTITY/d' "$project/project.pbxproj"
          done

      - name: Build iOS project
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     -allowProvisioningUpdates \
                     -allowProvisioningDeviceRegistration \
                     DEVELOPMENT_TEAM=X693B2FAZ3 \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="Apple Distribution" \
                     PROVISIONING_PROFILE_SPECIFIER="ProvProfileVPSDis" \
                     -archivePath ./build/App.xcarchive \
                     archive
      - name: Export IPA
        script: |
          cd ios/App
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>X693B2FAZ3</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.vapaesa</key>
              <string>ProvProfileVPSDis</string>
            </dict>
            <key>destination</key>
            <string>export</string>
            <key>compileBitcode</key>
            <true/>
            <key>stripSwiftSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
                     -archivePath ./build/App.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath ./build
    artifacts:
      - ios/App/build/**/*.ipa
