workflows:
  ios-ionic-release:
    name: iOS Ionic Release
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.vapaesa
        provisioning_profiles:
          - ProfileVPS.mobileprovision
        certificate_url: CertVPS.p12
        certificate_password: YOUR_CERT_PASSWORD
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      cocoapods: default
      node: 18.16.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build Ionic project
        script: |
          npm run build
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Build iOS app
        script: |
          xcodebuild clean archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_archive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=X693B2FAZ3 \
            PROVISIONING_PROFILE_SPECIFIER=ProfileVPS \
            PRODUCT_BUNDLE_IDENTIFIER=com.vapaesa
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_archive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_export
    artifacts:
      - ios_export/*.ipa
