workflows:
  ios-workflow:
    name: Build iOS
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.vapaesa"
        APP_NAME: "VapaesaApp"
        CERTIFICATE_PASSWORD: "Uh1dtx0*"
      node: 20.0.0
      xcode: latest
    scripts:
      - name: Install Ionic CLI
        script: |
          npm install -g @ionic/cli
      - name: Install dependencies
        script: |
          npm ci
      - name: Build Ionic web assets
        script: |
          ionic build --prod
      - name: Sync Capacitor for iOS
        script: |
          ionic cap sync ios
      - name: Prepare iOS
        script: |
          cd ios/App
          pod install
      - name: Import provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp certs/CodeMagicProvProfileVapaesa.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Import signing certificate
        script: |
          security delete-keychain build.keychain || true
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certs/CodeMagicCertVapaesa.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
      - name: Build iOS project
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     -allowProvisioningUpdates \
                     -allowProvisioningDeviceRegistration \
                     DEVELOPMENT_TEAM=X693B2FAZ3 \
                     CODE_SIGN_STYLE=Automatic \
                     -archivePath ./build/App.xcarchive \
                     archive
      - name: Export IPA
        script: |
          cd ios/App
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>teamID</key>
            <string>X693B2FAZ3</string>
            <key>destination</key>
            <string>export</string>
            <key>compileBitcode</key>
            <true/>
            <key>stripSwiftSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
                     -archivePath ./build/App.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath ./build
    artifacts:
      - ios/App/build/**/*.ipa
