workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_PROJECT: "App.xcworkspace"
        XCODE_SCHEME: "App"
        EXPORT_OPTIONS: "ios/ExportOptions.plist"
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Build archive
        script: |
          xcode-project build-archive \
            --workspace "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
      - name: Export IPA
        script: |
          xcode-project export-archive \
            --export-options-plist "$EXPORT_OPTIONS"
    artifacts:
      - build/ios/ipa/*.ipa
