workflows:
  ios-workflow:
    name: Build iOS 100% automático
    instance_type: mac_mini_m1

    environment:
      groups:
        - app_store_credentials    # Solo tu API Key de App Store Connect

      vars:
        BUNDLE_ID:        "com.vapaesa"
        DEVELOPMENT_TEAM: "X693B2FAZ3"
        WORKSPACE_PATH:   "ios/App/App.xcworkspace"
        SCHEME:           "App"

      node:      20.11.1
      xcode:     latest
      cocoapods: default

    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Fetch signing files (auto .p12 + .mobileprovision)
        script: |
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Install deps & build web
        script: |
          npm ci
          npm install -g @ionic/cli
          ionic build --prod
          ionic cap sync ios

      - name: CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Build signed .ipa (sin plist en repo)
        script: |
          cd ios/App
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace "$WORKSPACE_PATH" \
            --scheme "$SCHEME"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa