workflows:
  ios-appstore:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        EXPORT_OPTIONS: "ExportOptions.plist"
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Build and export IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "$EXPORT_OPTIONS"
    artifacts:
      - build/ios/ipa/*.ipa
