workflows:
  ios-manual-signing:
    name: iOS Build with Manual Signing
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_IDENTIFIER: "com.vapaesa"
        TEAM_ID: "X693B2FAZ3"
        PROVISIONING_PROFILE_SPECIFIER: "ProvProfileVPSDis"
        CODE_SIGN_IDENTITY: "Apple Distribution"
      xcode: 16.4
      cocoapods: default
    scripts:
      - name: Clean build artifacts
        script: |
          rm -rf ~/output
          mkdir -p ~/output
      - name: Install dependencies
        script: |
          cd ios/App
          pod install
      - name: Build and archive manually signed .xcarchive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$HOME/output/App.xcarchive" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$APP_IDENTIFIER" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
            clean archive
    artifacts:
      - ~/output/App.xcarchive
