workflows:
  ios-ionic-release:
    name: iOS Ionic Release
    environment:
      xcode: latest
      cocoapods: default
      node: 18.16.0
      signing:
        provisioning_profiles:
          - match AppStore com.vapaesa
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build Ionic Web Assets
        script: |
          npm run build
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS App with Automatic Signing
        script: |
          xcodebuild clean archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_archive \
            -allowProvisioningUpdates
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_archive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios_export \
            -allowProvisioningUpdates
    artifacts:
      - ios_export/*.ipa
    publishing:
      email:
        recipients:
          - tu-correo@example.com
        notify:
          success: true
          failure: true
