workflows:
  ios-ionic-build:
    name: Ionic iOS Build
    max_build_duration: 60
    environment:
      vars:
        BUNDLE_ID: "com.vapaesa"
        APPLE_ID: "vapaesacolombia@gmail.com" # <- cambia esto
      node: 20.10.0
      xcode: 16.4
      cocoapods: default
      flutter: false
      java: 17
      ruby: default
      npm: default
      groups:
        - app-store-credentials
        - certificate_credentials
      signing:
        provisioning_profiles:
          - ProfileVPS.mobileprovision
        certificates:
          - CertVPS.p12
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @ionic/cli
      - name: Build Ionic project
        script: |
          ionic build
      - name: Add iOS platform and prepare Cordova
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS project
        script: |
          cd ios/App
          xcodebuild clean archive \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER=ProfileVPS \
            DEVELOPMENT_TEAM=$CM_DEVELOPER_TEAM \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ipa
    artifacts:
      - build/ipa/*.ipa
